---
title: "Template + Case Studies"
---

### **Template Code**
Use these R Script and Rmd Markdown template scripts for your own _Coding for Broader Impact_ projects. They can be downloaded (cloned) with the repository or downloaded individually at the links here:  

  * [Iteration R Script - Template](https://github.com/dbturner/c4bi/blob/main/report_code/template/template_rScript.R)  
  * [Report RMarkdown - Template](https://github.com/dbturner/c4bi/blob/main/report_code/template/template_rmd.Rmd)  
  * [Sample Reports - Template](https://dbturner.github.io/c4bi/articles/template_examples_vignette.html)  
  
  
### **Case Studies**
_Case Study #1: Curaçao Homeowner Reports_  

  * [Iteration R Script - Homeowner Reports](https://github.com/dbturner/c4bi/blob/main/report_code/homeowner_reports/homeownerReports_rScript.R)  
  * [Report RMarkdown - Homeowner Reports](https://github.com/dbturner/c4bi/blob/main/report_code/homeowner_reports/homeownerReports_rmd.Rmd)  
  * [Sample Reports - Curaçao Homeowners](https://dbturner.github.io/c4bi/articles/homeownerReport1_examples_vignette.html)


  
_Case Study #2: Southeastern Pennsylvania (USA) Farmer Reports - First Iteration_  

  * [Iteration R Script - First Farmer Reports](https://github.com/dbturner/c4bi/blob/main/report_code/farmer_reports_iter1/farmerReports1_rScript.R)  
  * [Report RMarkdown - First Farmer Reports](https://github.com/dbturner/c4bi/blob/main/report_code/farmer_reports_iter1/farmerReports1_rmd.Rmd)  
  * [Sample Reports - Southeastern PA Farmers (First iteration)](https://dbturner.github.io/c4bi/articles/farmerReport1_examples_vignette.html)  
  * [Farmer Questions (see paper)](https://dbturner.github.io/c4bi/articles/farmer_questions_vignette.html)

_Case Study #2: Southeastern Pennsylvania Farmer Reports - Second Iteration_  
  
  * [Iteration R Script - Second Farmer Reports](https://github.com/dbturner/c4bi/blob/main/report_code/tick_reports/tickReports_Rscript.R)  
  * [Report RMarkdown - Second Farmer Reports](https://github.com/dbturner/c4bi/blob/main/report_code/farmer_reports_iter2/farmerReports2_rmd.Rmd)  
  * [Sample Reports - Southeastern PA Farmers (Second iteration)](https://dbturner.github.io/c4bi/articles/farmerReport2_examples_vignette.html)  

_Case Study #3 : Southeastern Pennsylvania Property Manager (Tick) Reports_

  * [Iteration R Script - Tick Reports](https://github.com/dbturner/c4bi/blob/main/report_code/tick_reports/tickReports_Rscript.R)  
  * [Report RMarkdown - Tick Reports](https://github.com/dbturner/c4bi/blob/main/report_code/tick_reports/tickReports_rmd.Rmd)  
  * [Sample Reports - Tick Reports](https://dbturner.github.io/c4bi/articles/tickReport1_examples_vignette.html)
  
  

